'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("QM_TEST.SVRCONN")>  _
        Public Property MQ_QMGR_Custom_Channel_Name() As String
            Get
                Return CType(Me("MQ_QMGR_Custom_Channel_Name"),String)
            End Get
            Set
                Me("MQ_QMGR_Custom_Channel_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.2.154")>  _
        Public Property MQ_QMGR_Host_Name() As String
            Get
                Return CType(Me("MQ_QMGR_Host_Name"),String)
            End Get
            Set
                Me("MQ_QMGR_Host_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("QM_infocor2")>  _
        Public Property MQ_QMGR_Queue_Manager() As String
            Get
                Return CType(Me("MQ_QMGR_Queue_Manager"),String)
            End Get
            Set
                Me("MQ_QMGR_Queue_Manager") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("II.ARP.REQUEST.APP.SCAN.REPLY")>  _
        Public Property MQ_Datagram_Receive_Queue() As String
            Get
                Return CType(Me("MQ_Datagram_Receive_Queue"),String)
            End Get
            Set
                Me("MQ_Datagram_Receive_Queue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1414")>  _
        Public Property MQ_QMGR_Port() As String
            Get
                Return CType(Me("MQ_QMGR_Port"),String)
            End Get
            Set
                Me("MQ_QMGR_Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MQ_Datagram_Receive_Wait_Interval() As String
            Get
                Return CType(Me("MQ_Datagram_Receive_Wait_Interval"),String)
            End Get
            Set
                Me("MQ_Datagram_Receive_Wait_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MQ_Datagram_Send_Timeout_Interval() As String
            Get
                Return CType(Me("MQ_Datagram_Send_Timeout_Interval"),String)
            End Get
            Set
                Me("MQ_Datagram_Send_Timeout_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("II.ARP.REQUEST.APP.SCAN")>  _
        Public Property MQ_Datagram_Send_Queue() As String
            Get
                Return CType(Me("MQ_Datagram_Send_Queue"),String)
            End Get
            Set
                Me("MQ_Datagram_Send_Queue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("II.ARP.REQUEST.APP.STATUS")>  _
        Public Property MQ_SendRequestReply_Queue() As String
            Get
                Return CType(Me("MQ_SendRequestReply_Queue"),String)
            End Get
            Set
                Me("MQ_SendRequestReply_Queue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MQ_SendRequestReply_Timeout_Interval() As String
            Get
                Return CType(Me("MQ_SendRequestReply_Timeout_Interval"),String)
            End Get
            Set
                Me("MQ_SendRequestReply_Timeout_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("II.ARP.REQUEST.APP.STATUS.REPLY")>  _
        Public Property MQ_SendRequestReply_ReplyQueue() As String
            Get
                Return CType(Me("MQ_SendRequestReply_ReplyQueue"),String)
            End Get
            Set
                Me("MQ_SendRequestReply_ReplyQueue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("II.PLUS.ARP.RESP")>  _
        Public Property MQ_GetRequestReply_RequestQueue() As String
            Get
                Return CType(Me("MQ_GetRequestReply_RequestQueue"),String)
            End Get
            Set
                Me("MQ_GetRequestReply_RequestQueue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property MQ_GetRequestReply_Timeout_Interval() As String
            Get
                Return CType(Me("MQ_GetRequestReply_Timeout_Interval"),String)
            End Get
            Set
                Me("MQ_GetRequestReply_Timeout_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Datagram_Send_Msgs() As String
            Get
                Return CType(Me("Datagram_Send_Msgs"),String)
            End Get
            Set
                Me("Datagram_Send_Msgs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Datagram_Receive_Msgs() As String
            Get
                Return CType(Me("Datagram_Receive_Msgs"),String)
            End Get
            Set
                Me("Datagram_Receive_Msgs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Send_Request_Msgs() As String
            Get
                Return CType(Me("Send_Request_Msgs"),String)
            End Get
            Set
                Me("Send_Request_Msgs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Get_Request_Msgs() As String
            Get
                Return CType(Me("Get_Request_Msgs"),String)
            End Get
            Set
                Me("Get_Request_Msgs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property Timer_Interval() As String
            Get
                Return CType(Me("Timer_Interval"),String)
            End Get
            Set
                Me("Timer_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ValidateMsgFormat() As Boolean
            Get
                Return CType(Me("ValidateMsgFormat"),Boolean)
            End Get
            Set
                Me("ValidateMsgFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableMQAppStatus() As Boolean
            Get
                Return CType(Me("EnableMQAppStatus"),Boolean)
            End Get
            Set
                Me("EnableMQAppStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableMQAppRequest() As Boolean
            Get
                Return CType(Me("EnableMQAppRequest"),Boolean)
            End Get
            Set
                Me("EnableMQAppRequest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableMQAppReply() As Boolean
            Get
                Return CType(Me("EnableMQAppReply"),Boolean)
            End Get
            Set
                Me("EnableMQAppReply") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property InvalidMsg() As String
            Get
                Return CType(Me("InvalidMsg"),String)
            End Get
            Set
                Me("InvalidMsg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MQ_SecurityExit() As String
            Get
                Return CType(Me("MQ_SecurityExit"),String)
            End Get
            Set
                Me("MQ_SecurityExit") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MQTestClient.My.MySettings
            Get
                Return Global.MQTestClient.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
